In [62]:
import pandas as pd

In [63]:
data = {
    'Car name': ['A2', 'C3', 'D2', 'A3', 'C6'],
    'Type': ['Sedan', 'SUV', 'Hatchback', 'Sedan', 'MUV'],
    'Brand': ['ASP', 'TRE', 'ASP', 'TOY', 'TOY'],
    'Price (in lakhs)': [15, 20, 14, 13, 18]
}

In [64]:
df=pd.DataFrame(data)

In [65]:
type(df)

pandas.core.frame.DataFrame

In [66]:
df

  Car name       Type Brand  Price (in lakhs)
0       A2      Sedan   ASP                15
1       C3        SUV   TRE                20
2       D2  Hatchback   ASP                14
3       A3      Sedan   TOY                13
4       C6        MUV   TOY                18

In [67]:
df[['Type']]

        Type
0      Sedan
1        SUV
2  Hatchback
3      Sedan
4        MUV

In [68]:
df.iloc[:, 1]

0        Sedan
1          SUV
2    Hatchback
3        Sedan
4          MUV
Name: Type, dtype: object

In [69]:
df.loc[:, ['Type']]

        Type
0      Sedan
1        SUV
2  Hatchback
3      Sedan
4        MUV

In [70]:
df.describe()

       Price (in lakhs)
count          5.000000
mean          16.000000
std            2.915476
min           13.000000
25%           14.000000
50%           15.000000
75%           18.000000
max           20.000000

In [71]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5']
})

result = pd.concat([df1, df2], axis=0)
print(result)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  A3  B3
1  A4  B4
2  A5  B5

In [72]:
data1 = {
    "Variable": [
        "ID",
        "Company",
        "Bean Origin",
        "Review Data",
        "Cocoa percent",
        "Company Location",
        "Rating"
    ],
    "Description": [
        "Serial no.",
        "Name of a manufacturing company",
        "Place of origin of cocoa bean",
        "Year in which chocolates were rated",
        "Percentage of cocoa in chocolate",
        "Location of a manufacturing company",
        "Rating of chocolates"
    ]
}

# Create the DataFrame
df_cocoa = pd.DataFrame(data1)

In [73]:
df_cocoa

           Variable                          Description
0                ID                           Serial no.
1           Company      Name of a manufacturing company
2       Bean Origin        Place of origin of cocoa bean
3       Review Data  Year in which chocolates were rated
4     Cocoa percent     Percentage of cocoa in chocolate
5  Company Location  Location of a manufacturing company
6            Rating                 Rating of chocolates

In [74]:
df_cocoa.isnull().sum()

Variable       0
Description    0
dtype: int64

In [75]:
import numpy as np
B = [True, 2, 3.0, np.nan, "False"]
[type(i) for i in B]

[bool, int, float, float, str]

In [76]:
arr=np.array([1,2,3,4,5])
print(arr[::2])

[1 3 5]

In [77]:
# def remdup(li):
#     new=li
#     count=0
#     for i in range(0,len(li)):
#         for j in range(0,len(li)):
#             if li[i]==li[j]:
#                 new.pop(i-count)
#                 count=count+1
#     return new


def remdup(l):
    seen = set()
    new_list = []
    for item in reversed(l):
        if item not in seen:
            seen.add(item)
            new_list.append(item)
    return new_list[::-1]

In [78]:
# Test cases
print(remdup([3, 1, 3, 5]))  # Output: [1, 3, 5]
print(remdup([7, 3, -1, -5]))  # Output: [7, 3, -1, -5]
print(remdup([3, 5, 7, 5, 3, 7, 10]))  # Output: [5, 3, 7, 10]

[1, 3, 5]
[7, 3, -1, -5]
[5, 3, 7, 10]

In [81]:
def splitsum(l):
    pos=0
    neg=0
    for i in l:
        if i>=0:
            pos=pos+(i**2)
        else:
            neg=neg+(i**3)
    return [pos,neg]

In [82]:
splitsum([1,3,-5])

[10, -125]

In [83]:
splitsum([2,4,6])

[56, 0]

In [84]:
splitsum([-19,-7,-6,0])

[0, -7418]

In [85]:
splitsum([-1,2,3,-7])

[13, -344]

In [87]:
def matrixflip(m,d):
    if d=='h':
        return [i[::-1] for i in m]
    elif d=='v':
        return m[::-1]
    else: 
        return m

In [89]:
myl = [[1,2],[3,4]]
myl

[[1, 2], [3, 4]]

In [90]:
matrixflip(myl,'h')
# [[2, 1], [4, 3]]

[[2, 1], [4, 3]]

In [91]:
myl
# [[1, 2], [3, 4]]

[[1, 2], [3, 4]]

In [92]:
matrixflip(myl,'v')
# [[3, 4], [1, 2]]

[[3, 4], [1, 2]]

In [94]:
myl
# [[1, 2], [3, 4]]

[[1, 2], [3, 4]]

In [ ]:
matrixflip(matrixflip(myl,'h'),'v')
# [[4, 3], [2, 1]]

[[4, 3], [2, 1]]

In [96]:
myl
# [[1, 2], [3, 4]]

[[1, 2], [3, 4]]

In [97]:
matrixflip(matrixflip(myl,'h'),'v')
# [[4, 3], [2, 1]]

[[4, 3], [2, 1]]

In [98]:
myl
# [[1, 2], [3, 4]]

[[1, 2], [3, 4]]

In [99]:
a= [1, 2] + [3, 4]
a

[1, 2, 3, 4]